### PR TITLE
include response in error if parsing failed

### PR DESCRIPTION
**Pull request by petli-openshift**
Some logs show `EOF` or `Invalid char <`. I think we can include the raw response in the error if the response can not be parsed into JSON.

It provides more context for their logs. However, it's not absolutely needed, since we have status code.

### CODE REVIEW

**Comment by cben** [comment]
Good idea.  But cases like "Invalid char <" mean you're getting html from some other proxy/service, which could be huge. Maybe truncate it to some length? 100? 1000?

**Comment by jhernand** [comment]
I'd prefer to put this logic in the `send` method of the SDK instead of repeating it every generated client. I mean here: https://github.com/openshift-online/ocm-sdk-go/blob/0000a0e2af908a7fafa82e3ebd43579f5790b4af/send.go#L191

I'd also suggest to change that `send` method so that it checks that the response received contains the `Content-Type: application/json; ...` header. If it doesn't then we shouldn't even try to parse the body.

The error returned in those cases should be something like `expected JSON content type but received 'application/html'`.

**Comment by cben** [comment]
> The error returned in those cases should be something like expected JSON content type but received 'application/html'.

From my experience, that usually means the response came from some different service, and seeing at least part of the response is useful to figure out who that is and debug the issue.  
[Real example from another product: customer corp firewall, a week wasted on guesses, once they realized that's the source, they quickly whitelisted the domain.]
However, if logs don't contain the data, it's usually easy to reproduce with `curl`.

**Comment by jhernand** [comment]
I have no objection to show part of the response content in the error message. Just saying that the value of the offending `Content-Type` header should also be included in the error message.

**Comment by petli-openshift** [comment]
@jhernand @cben thanks for the suggests. I moved it https://github.com/openshift-online/ocm-sdk-go/pull/133. I am closing this MR.

**Pull request closed without merging**
