### PR TITLE
Use gingko v1.10.3 in PR check

### PR DESCRIPTION
**Pull request by igoihman**

### CODE REVIEW

**Comment by igoihman** [comment]
@vkareh looks like `goimports` is problematic as well, I will use a specific version as well.

**Comment by vkareh** [comment]
[test]

**Comment by vkareh** [comment]
yes, probably a good idea

**Comment by vkareh** [comment]
tests seem to be running now, often happens with the explicit `[test]`

**Comment by vkareh** [comment]
very nice, thanks a bunch!

**Pull request merged**
